#! /bin/bash -e

d=$(date --iso-8601=date)

folder=/tmp/otp-speed-test/

file=/tmp/otp-speed-test-${d}.zip

influxd backup -portable -database performance ${folder}

# restore with:
# sudo influxd restore -db performance -newdb performance -datadir /var/lib/influxdb/data -metadir /var/lib/influxdb/meta /home/lenni/tmp/otp-speed-test/
# sudo chown -R influxdb:influxdb /var/lib/influxdb/
# sudo systemctl restart influxdb.service

zip -r "${file}" $folder

echo "Sending file to off-site storage"
curl --silent --show-error --fail -T "${file}" -u 'otp-backup:{{ otp_backup_password }}' "https://nextcloud.leonard.io/remote.php/dav/files/otp-backup/otp-speed-test/"

rm "$file"
rm -rf $folder

systemctl restart influxdb
