#! /bin/bash -ex

tables=(
  raptor_Mc-DP_route
  raptor_MinTravelDuration-Rev_route
  raptor_MinTravelDurationBT-Rev_route
  raptor_MinTravelDuration_route
  raptor_NoWaitBT-Rev_route
  routing_accessEgress
  routing_directStreet
  routing_filtering
  routing_raptor
  routing_total
  routing_transit
  routing_tripPatternFiltering
)

for i in "${tables[@]}"
do
  #influx -username performance -database performance -password {{ influxdb_password }} -execute "SELECT time,mean(mean) INTO \"${i}_aggregated\" FROM \"${i}\" GROUP BY time(10m),location,git_commit,tags,TestCaseCategory,git_branch"
  influx -username performance -database performance -password {{ influxdb_password }} -execute "CREATE CONTINUOUS QUERY \"cq_${i}_aggregate\" ON \"performance\" BEGIN SELECT time,mean(mean) INTO \"${i}_aggregated\" FROM \"${i}\" GROUP BY time(10m),location,git_commit,tags,TestCaseCategory,git_branch END"
done


